[package]
name = "backend"
version = "0.1.0"
authors = ["Jill Enke <jill.enke@gmail.com>"]
edition = "2018"

[lib]
name = "pixie_backend"
crate-type = ["cdylib"]

[dependencies]
serenity = "0.7.0"

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]