INSERT INTO "public"."pb_user" ("user_name", "user_discord_id") VALUES (E'demo_user', E'demo_user#0001');
INSERT INTO "public"."pb_user" ("user_name", "user_discord_id") VALUES (E'robjackson', E'robjackson#0357');
INSERT INTO "public"."pb_user" ("user_name", "user_discord_id") VALUES (E'donaldasullivan82', E'donaldasullivan82#0741');
INSERT INTO "public"."pb_server" ("server_name") VALUES (E'demo_server');
INSERT INTO "public"."pb_server" ("server_name") VALUES (E'Map Fighters');
INSERT INTO "public"."pb_server" ("server_name") VALUES (E'England Panic');
INSERT INTO "public"."pb_bot" ("bot_name", "server_id") VALUES (E'demo_bot', E'1');
INSERT INTO "public"."pb_bot" ("bot_name", "server_id") VALUES (E'Rough-Mouse', E'1');
INSERT INTO "public"."pb_bot" ("bot_name", "server_id") VALUES (E'Captain Creep', E'2');
INSERT INTO "public"."pb_bot" ("bot_name", "server_id") VALUES (E'Agent Steal', E'2');
INSERT INTO "public"."pb_bot" ("bot_name", "server_id") VALUES (E'Impressive-Man', E'3');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Zufriedenheit ist der Stein der Weisen, der alles, was er berührt, in Gold verwandelt; der Arme ist reich mit ihm, der Reiche arm ohne ihn.', E'1780', E'Benjamin Franklin', E'1', E'1');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Die besten Dinge im Leben sind nicht die, die man für Geld bekommt.', E'1945', E'Albert Einstein', E'2', E'1');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Heutzutage kennen die Leute von allem den Preis und nicht den Wert.', E'1867', E'Oscar Wilde', E'3', E'2');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Die Zeit heilt alle Wunden.', E'1766', E'Benjamin Franklin', E'2', E'2');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Die Zeit mag Wunden heilen, aber sie ist eine miserable Kosmetikerin.', E'1900', E'Mark Tawin', E'1', E'3');
INSERT INTO "public"."pb_quotes" ("quotes_content", "quotes_date", "quotes_author", "user_id", "server_id") VALUES (E'Wenn ein Land für Freiheit steht, dann ist das China.', E'2019', E'Kai Pflaume', E'3', E'3');
INSERT INTO "public"."pb_birthday" ("bday_date", "bday_name", "user_id", "server_id") VALUES (E'05.01.1975', E'Bradley Cooper', E'2', E'1');
INSERT INTO "public"."pb_birthday" ("bday_date", "bday_name", "user_id", "server_id") VALUES (E'13.05.1950', E'Stevie Wonder', E'1', E'3');
INSERT INTO "public"."pb_birthday" ("bday_date", "bday_name", "user_id", "server_id") VALUES (E'12.08.1954', E'François Hollande', E'3', E'2');
